select
    COMPANY_ID,
    CU_COMPANY_L2_INDUSTRY,
    AVG_USD_AMT_ALL_MAKE,
    AVG_NET_REVENUE_USD_AMT_ALL_MAKE,
    FREQ_ACTIVE_MAKE,
    PAYTYPE_COUNT_ALL_MAKE,
    SUPPLIER_PAYMENT_PERCENT_MAKE,
    RENT_PAYMENT_PERCENT_MAKE,
    PAYROLL_PAYMENT_PERCENT_MAKE,
    MONTHS_SINCE_FIRST_PAYMENT_ALL_MAKE,
    MONTHS_SINCE_LAST_PAYMENT_ALL_MAKE,
    RSD_PERCENTAGE_MAKE,
    USE_COLLECT
from
    DEV.SBOX_SHILTON.CU_B2B_INDUSTRY_SEGMENTATION_MAIN_TABLE
where
    CU_COMPANY_L1_INDUSTRY = 'Food and Beverages';