select
    COMPANY_ID,
    CU_COMPANY_L2_INDUSTRY,
    AVG_USD_AMT_ALL_MAKE,
    AVG_REVENUE_USD_AMT_ALL_MAKE,
    AVG_NET_REVENUE_USD_AMT_ALL_MAKE,
    FREQ_ACTIVE_MAKE,
    PAYTYPE_COUNT_ALL_MAKE,
    SUPPLIER_PAYMENT_PERCENT_MAKE,
    RENT_PAYMENT_PERCENT_MAKE,
    PAYROLL_PAYMENT_PERCENT_MAKE,
    MONTHS_SINCE_FIRST_PAYMENT_ALL_MAKE,
    MONTHS_SINCE_LAST_PAYMENT_ALL_MAKE,
    RSD_PERCENTAGE_MAKE,
    USE_COLLECT,
    ENTITY_NAME,

    AVG_USD_AMT_ALL_COLLECT,
    AVG_REVENUE_USD_AMT_ALL_COLLECT,
    AVG_NET_REVENUE_USD_AMT_ALL_COLLECT,
    FREQ_ACTIVE_COLLECT,
    PAYTYPE_COUNT_ALL_COLLECT,
    SUPPLIER_PAYMENT_PERCENT_COLLECT,
    RENT_PAYMENT_PERCENT_COLLECT,
    PAYROLL_PAYMENT_PERCENT_COLLECT,
    MONTHS_SINCE_FIRST_PAYMENT_ALL_COLLECT,
    MONTHS_SINCE_LAST_PAYMENT_ALL_COLLECT,
from
    DEV.SBOX_SHILTON.CU_B2B_INDUSTRY_SEGMENTATION_MAIN_TABLE
where
    CU_COMPANY_L1_INDUSTRY = 'Wholesale'
    and (avg_revenue_usd_amt_all_collect is not null or avg_revenue_usd_amt_all_make is not null);